apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.Master.AdminPassword }}
  ldap-admin-password:  {{ .Values.Master.AdminPassword | b64enc | quote }}
  {{ else }}
  ldap-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
