---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  relay.yaml: |-
    hostname: "relay"
    fqdn: "relay.{{ .Values.global.domain }}"
    defaultUser: {{ .Values.global.relayDefaultUser | quote }}
    relayHost: {{ .Values.global.relayHost | quote }}
    sendgrid:
      username: {{ .Values.global.relaySendgridUsername | quote }}
      password: {{ .Values.global.relaySendgridPassword | quote }}
    
