apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  create-jira-db.sql: |-
    DROP USER IF EXISTS 'jira'@'%';
    CREATE USER 'jira'@'%' IDENTIFIED BY '{{ .Values.global.jiraDbPassword }}';
    CREATE DATABASE IF NOT EXISTS jiradb;
    GRANT ALL PRIVILEGES ON jiradb.* TO 'jira'@'%';
