apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ template "jira" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"

spec:
  rules:
  - host: "jira.{{ .Values.global.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "jira" . }}
          servicePort: 8080

  tls:
    - secretName:  "tls-jira.{{ .Values.global.domain }}"
      hosts:
        - "jira.{{ .Values.global.domain }}"
